# Generated by Django 5.1.5 on 2025-02-02 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0004_rename_user_cart_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer',
            new_name='customer_name',
        ),
    ]
