# Generated by Django 5.1.5 on 2025-03-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0012_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
